use_frameworks!

platform :ios, '10.0'

target 'HYBaseTool_Example' do
  pod 'HYBaseTool', :path => '../'

#  pod 'QMUIKit'
#  pod 'Masonry'

  target 'HYBaseTool_Tests' do
    inherit! :search_paths


  end
end
